[package]
name = "reference-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twox-hash = "1.6.3"
clap = { version = "4.4.8", features = ["derive"] }

